name: hicon-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  # test dependencies
  - pytest>=6.0
  - pytest-cov

  # required dependencies
  - setuptools
  - black

  # optional dependencies
  - jupyterlab

#  - pip:
#      - jupyterlite==0.1.0b12
#      - sphinx-toggleprompt
